blank_issues_enabled: false
contact_links:
  - name: Security Issue Report
    url: https://github.com/your-repo/security
    about: Please do not open security issues publicly. Report vulnerabilities via email.
